<a href="https://colab.research.google.com/github/sreekarjallepalli/Data-Science/blob/main/DS_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

original_array = np.arange(15, 31)
print("Original 1D array (values from 15 to 30):")
print(original_array)
print(f"Number of elements: {original_array.size}")

reshaped_array = original_array.reshape((4, 4))
print("\nReshaped 2D array (4 rows, 4 columns):")
print(reshaped_array)
print(f"Shape of the reshaped array: {reshaped_array.shape}")

reshaped_array_2 = original_array.reshape((2, 8))
print("\nReshaped 2D array (2 rows, 8 columns):")
print(reshaped_array_2)
print(f"Shape of the reshaped array: {reshaped_array_2.shape}")

Original 1D array (values from 15 to 30):
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
Number of elements: 16

Reshaped 2D array (4 rows, 4 columns):
[[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]
Shape of the reshaped array: (4, 4)

Reshaped 2D array (2 rows, 8 columns):
[[15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30]]
Shape of the reshaped array: (2, 8)
